FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY ./python/requirements.txt /tmp/requirements.txt
RUN \
    apt-get update && \
    apt-get install -y --no-install-recommends postgresql-client gzip && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir -r /tmp/requirements.txt && \
    rm -f requirements.txt

COPY ./python/ /app/

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
