ALTER TABLE users
    ADD COLUMN IF NOT EXISTS avatar_icon_id UUID REFERENCES icon_assets(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ NULL;
