ALTER TABLE accounts
    ADD COLUMN IF NOT EXISTS closed BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS max_credit_cents INTEGER NULL,
    ADD COLUMN IF NOT EXISTS rewards_balance_cents INTEGER NULL;
